variables:
  CONTAINER_IMAGE: registry.gitlab.com/daonm/$CI_PROJECT_NAME
  STABLE_IMAGE_TAG: $CI_COMMIT_REF_SLUG-latest-stable
  ARCHIVE_IMAGE_TAG: $CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA
  CREDENTIALS_DEV: "/home/node/credential/be/.env.development"
  CREDENTIALS_PROD: "/home/node/credential/be/.env.production"
  SLEEP_WHEN_START_CONTAINER: 10

stages:
    - build
    - deploy

before_script:
  - echo CI_BUILD_TOKEN
  - echo $CI_JOB_TOKEN
  - echo $CI_REGISTRY
  - sudo usermod -aG docker gitlab-runner
  - docker info
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - echo $USER

# STAGE BUILD DEVELOP
PRIME-EDU-DEVELOPMENT-BUILD:
    variables:
        EXPOSE_PORT: 4000
        STABLE_IMAGE_TAG: build-develop-latest
        IMAGE_NAME: $CONTAINER_IMAGE:$ARCHIVE_IMAGE_TAG
    stage: build
    tags: 
        - PRIME-EDU-BE-DEVELOP
    only:
        - develop
    script:
        - rm -rf .git
        - rm -rf .gitlab-ci.yml
        - rm -rf .gitattributes

        - cp -r $CREDENTIALS_DEV .env
        - echo "Building the image $IMAGE_NAME ...."
        - docker compose build --force-rm

        # Push Archive by commit tag
        - docker push $IMAGE_NAME

        # Push stable production
        - docker tag $IMAGE_NAME $CONTAINER_IMAGE:$STABLE_IMAGE_TAG
        - docker push $CONTAINER_IMAGE:$STABLE_IMAGE_TAG

        # Remove unuse images
        - docker rmi $(docker images -qf dangling=true) || true
        - echo "Build complete."

# STAGE DELOY DEVELOP
PRIME-EDU-DEVELOPMENT-DELOY:
    variables:
        EXPOSE_PORT: 4000
        IMAGE_NAME: $CONTAINER_IMAGE:$ARCHIVE_IMAGE_TAG
        CONTAINER_NAME: prime-edu-be-develop
    stage: deploy
    tags:
        - PRIME-EDU-BE-DEVELOP
    only:
        - develop
    script:
        - rm -rf .git
        - rm -rf .gitlab-ci.yml
        - rm -rf .gitattributes

        - echo "Build container $CONTAINER_NAME from $IMAGE_NAME for testing ..."
        - docker pull $IMAGE_NAME

        # Only run the services defined in docker-compose.yml
        - docker compose up -d  --remove-orphans

        - docker logs $CONTAINER_NAME
        - docker rmi $(docker images -qf dangling=true) || true

    when: on_success
