version: '3.9'
services:
  backendapi:
    build:
      context: .
    image: $IMAGE_NAME
    container_name: prime-edu-be-develop
    expose:
      - "4000"
    environment:
      - VIRTUAL_HOST=staging.primeedu.io.vn
      - VIRTUAL_PORT=4000
      - VIRTUAL_PATH=/api
      - VIRTUAL_PROTO=https
    restart: always
  nginx:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"
    restart: always