version: '3.9'
services:
  backendapi:
    build:
      context: .
    image: $IMAGE_NAME
    container_name: prime-edu-be-develop
    ports:
      - "$EXPOSE_PORT:4000"
    restart: always
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    restart: always