version: '3.9'
services:
  backendapi:
    build:
      context: .
    image: $IMAGE_NAME
    container_name: prime-edu-be-develop
    ports:
      - "$EXPOSE_PORT:4000"
    restart: always
  nginx:
    image: nginxproxy/nginx-proxy
    container_name: nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"
    # restart: always
